# Generated by Django 6.0.3 on 2026-04-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2026-04-07'),
        ),
    ]
