# Generated by Django 6.0.3 on 2026-04-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0002_user_foto_alter_tarea_fecha_creación'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lun', 'Lun'), ('Mar', 'Mar'), ('Mié', 'Mié'), ('Jue', 'Jue'), ('Vie', 'Vie'), ('Sáb', 'Sáb')], max_length=5)),
                ('hora', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'dia', 'hora')},
            },
        ),
    ]
