# Generated by Django 6.0.3 on 2026-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0003_bloquehorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('depto', models.CharField(choices=[('DFI', 'DFI'), ('DIM', 'DIM'), ('Otros', 'Otros')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ramos',
            field=models.ManyToManyField(blank=True, to='Prueba.ramo'),
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
