# Generated by Django 6.0.3 on 2026-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0004_ramo_user_precio_user_ramos_delete_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidad',
            field=models.CharField(choices=[('MINAS', 'Ingeniería Civil en Minas'), ('ELEC', 'Ingeniería Civil Eléctrica'), ('BIO', 'Ingeniería Civil en Biotecnología'), ('COMP', 'Ingeniería Civil en Computación'), ('IND', 'Ingeniería Civil Industrial'), ('MAT', 'Ingeniería Civil Matemática'), ('MEC', 'Ingeniería Civil Mecánica'), ('QUIM', 'Ingeniería Civil Química'), ('GEO', 'Geología'), ('FIS', 'Licenciatura en Física'), ('ASTRO', 'Licenciatura en Astronomía'), ('GEOF', 'Licenciatura en Geofísica')], default='COMP', max_length=10),
            preserve_default=False,
        ),
    ]
