# Generated by Django 6.0.3 on 2026-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0005_user_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='depto',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('Competencia Lectora', 'Competencia Lectora'), ('Historia y Cs. Sociales', 'Historia y Cs. Sociales'), ('Ciencias - Biología', 'Ciencias - Biología'), ('Ciencias - Física', 'Ciencias - Física'), ('Ciencias - Química', 'Ciencias - Química')], max_length=30),
        ),
    ]
