# Generated by Django 6.0.3 on 2026-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0006_alter_ramo_depto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pronombre',
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, choices=[('ing_civil', 'Ingeniería Civil'), ('ing_comercial', 'Ingeniería Comercial'), ('medicina', 'Medicina'), ('derecho', 'Derecho'), ('psicologia', 'Psicología'), ('pedagogia', 'Pedagogía'), ('arquitectura', 'Arquitectura'), ('administracion', 'Administración de Empresas'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='empleo',
            field=models.CharField(blank=True, choices=[('profesor', 'Profesor/a'), ('ingeniero', 'Ingeniero/a'), ('medico', 'Médico/a'), ('abogado', 'Abogado/a'), ('contador', 'Contador/a'), ('diseñador', 'Diseñador/a'), ('estudiante_posgrado', 'Estudiante de posgrado'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador')], default='estudiante', max_length=20),
        ),
    ]
