# Generated by Django 6.0.3 on 2026-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0008_reserva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('profesor', 'fecha', 'hora')},
        ),
    ]
