# Generated by Django 6.0.3 on 2026-04-09 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0009_alter_reserva_unique_together_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva_creada', 'Reserva creada'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_cancelada', 'Reserva cancelada')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_el'],
            },
        ),
    ]
