# Generated by Django 6.0.3 on 2026-04-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0010_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ramos_tomados',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='Prueba.ramo'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=15),
        ),
    ]
