# Generated by Django 6.0.3 on 2026-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0011_user_ramos_tomados_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
