# Generated by Django 4.2.11 on 2026-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0013_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('profesor', 'Profesor/a'), ('ingeniero', 'Ingeniero/a'), ('medico', 'Médico/a'), ('abogado', 'Abogado/a'), ('contador', 'Contador/a'), ('diseñador', 'Diseñador/a'), ('estudiante_posgrado', 'Estudiante de posgrado'), ('otro', 'Otro')], default='', max_length=30),
        ),
    ]
