# Generated by Django 4.2.11 on 2026-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0014_user_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('santiago', 'Santiago'), ('valparaiso', 'Valparaíso'), ('vina_del_mar', 'Viña del Mar'), ('concepcion', 'Concepción'), ('la_serena', 'La Serena'), ('coquimbo', 'Coquimbo'), ('antofagasta', 'Antofagasta'), ('iquique', 'Iquique'), ('arica', 'Arica'), ('rancagua', 'Rancagua'), ('talca', 'Talca'), ('chillan', 'Chillán'), ('temuco', 'Temuco'), ('puerto_montt', 'Puerto Montt'), ('valdivia', 'Valdivia'), ('osorno', 'Osorno'), ('punta_arenas', 'Punta Arenas'), ('calama', 'Calama'), ('copiapo', 'Copiapó'), ('los_andes', 'Los Andes'), ('san_antonio', 'San Antonio'), ('quilpue', 'Quilpué'), ('villa_alemana', 'Villa Alemana'), ('curico', 'Curicó'), ('linares', 'Linares'), ('san_felipe', 'San Felipe'), ('melipilla', 'Melipilla'), ('talcahuano', 'Talcahuano'), ('coronel', 'Coronel'), ('angol', 'Angol')], default='', max_length=30),
        ),
    ]
