TIPO_CHOICES = [
    ('estudiante', 'Estudiante'),
    ('trabajador', 'Trabajador'),
]

CARRERAS = [
    ('acuicultura',               'Acuicultura'),
    ('administracion',            'Administración de Empresas'),
    ('agronomia',                 'Agronomía'),
    ('antropologia',              'Antropología'),
    ('arquitectura',              'Arquitectura'),
    ('astronomia',                'Astronomía'),
    ('bellas_artes',              'Bellas Artes'),
    ('biologia',                  'Biología'),
    ('ciencia_politica',          'Ciencia Política'),
    ('computacion',               'Ciencias de la Computación'),
    ('ciberseguridad',            'Ciberseguridad'),
    ('cine',                      'Cine y Televisión'),
    ('comercio_exterior',         'Comercio Exterior'),
    ('comunicacion_audiovisual',  'Comunicación Audiovisual'),
    ('contador_auditor',          'Contador Auditor'),
    ('data_science',              'Data Science / Ciencia de Datos'),
    ('derecho',                   'Derecho'),
    ('disenio_interiores',        'Diseño de Interiores'),
    ('disenio_grafico',           'Diseño Gráfico'),
    ('disenio_industrial',        'Diseño Industrial'),
    ('economia',                  'Economía'),
    ('educacion_diferencial',     'Educación Diferencial'),
    ('educacion_parvularia',      'Educación Parvularia'),
    ('enfermeria',                'Enfermería'),
    ('estadistica',               'Estadística'),
    ('filosofia',                 'Filosofía'),
    ('finanzas',                  'Finanzas'),
    ('fisica',                    'Física'),
    ('fonoaudiologia',            'Fonoaudiología'),
    ('geografia',                 'Geografía'),
    ('geologia',                  'Geología'),
    ('medio_ambiente',            'Gestión Ambiental'),
    ('historia',                  'Historia'),
    ('ing_ambiental',             'Ingeniería Ambiental'),
    ('ing_biomedica',             'Ingeniería Biomédica'),
    ('ing_civil',                 'Ingeniería Civil'),
    ('ing_comercial',             'Ingeniería Comercial'),
    ('ing_electrica',             'Ingeniería Eléctrica'),
    ('ing_electronica',           'Ingeniería Electrónica'),
    ('ing_minas',                 'Ingeniería en Minas'),
    ('ing_telecomunicaciones',    'Ingeniería en Telecomunicaciones'),
    ('ingenieria_forestal',       'Ingeniería Forestal'),
    ('ing_industrial',            'Ingeniería Industrial'),
    ('ing_informatica',           'Ingeniería Informática'),
    ('ing_mecanica',              'Ingeniería Mecánica'),
    ('ing_quimica',               'Ingeniería Química'),
    ('kinesiologia',              'Kinesiología'),
    ('logistica',                 'Logística y Transporte'),
    ('marketing',                 'Marketing'),
    ('matematica',                'Matemática'),
    ('medicina',                  'Medicina'),
    ('medicina_veterinaria',      'Medicina Veterinaria'),
    ('musica',                    'Música'),
    ('nutricion',                 'Nutrición y Dietética'),
    ('obstetricia',               'Obstetricia'),
    ('odontologia',               'Odontología'),
    ('pedagogia',                 'Pedagogía'),
    ('pedagogia_ciencias',        'Pedagogía en Ciencias'),
    ('pedagogia_historia',        'Pedagogía en Historia'),
    ('pedagogia_ingles',          'Pedagogía en Inglés'),
    ('pedagogia_lenguaje',        'Pedagogía en Lenguaje'),
    ('pedagogia_matematica',      'Pedagogía en Matemática'),
    ('periodismo',                'Periodismo'),
    ('psicologia',                'Psicología'),
    ('publicidad',                'Publicidad'),
    ('quimica',                   'Química'),
    ('farmacia',                  'Química y Farmacia'),
    ('relaciones_internacionales','Relaciones Internacionales'),
    ('sociologia',                'Sociología'),
    ('teatro',                    'Teatro'),
    ('tecnologia_medica',         'Tecnología Médica'),
    ('terapia_ocupacional',       'Terapia Ocupacional'),
    ('trabajo_social',            'Trabajo Social'),
    ('turismo',                   'Turismo y Hotelería'),
    ('otro',                      'Otro'),
]

EMPLEOS = [
    ('abogado',              'Abogado/a'),
    ('analista_negocio',     'Analista de negocios'),
    ('analista_financiero',  'Analista financiero/a'),
    ('arquitecto',           'Arquitecto/a'),
    ('arquitecto_software',  'Arquitecto/a de software'),
    ('auditor',              'Auditor/a'),
    ('cientifico',           'Científico/a'),
    ('data_scientist',       'Científico/a de datos'),
    ('consultor',            'Consultor/a'),
    ('contador',             'Contador/a'),
    ('desarrollador',        'Desarrollador/a de software'),
    ('devops',               'DevOps / SRE'),
    ('disenador',            'Diseñador/a'),
    ('disenio_ux',           'Diseñador/a UX/UI'),
    ('docente_universitario','Docente universitario/a'),
    ('economista',           'Economista'),
    ('emprendedor',          'Emprendedor/a'),
    ('enfermero',            'Enfermero/a'),
    ('ciberseguridad',       'Especialista en ciberseguridad'),
    ('marketing',            'Especialista en marketing'),
    ('estadistico',          'Estadístico/a'),
    ('estudiante_posgrado',  'Estudiante de posgrado'),
    ('farmaceutico',         'Farmacéutico/a'),
    ('fotografo',            'Fotógrafo/a'),
    ('freelancer',           'Freelancer / Independiente'),
    ('funcionario_publico',  'Funcionario/a público/a'),
    ('gerente',              'Gerente / Director/a'),
    ('ingeniero',            'Ingeniero/a'),
    ('instructor',           'Instructor/a de capacitación'),
    ('investigador',         'Investigador/a'),
    ('kinesiologo',          'Kinesiólogo/a'),
    ('medico',               'Médico/a'),
    ('musico',               'Músico/a'),
    ('notario',              'Notario/a'),
    ('nutricionista',        'Nutricionista'),
    ('odontologo',           'Odontólogo/a'),
    ('periodista',           'Periodista'),
    ('product_manager',      'Product Manager'),
    ('productor_audiovisual','Productor/a audiovisual'),
    ('profesor',             'Profesor/a'),
    ('psicologo',            'Psicólogo/a'),
    ('publicista',           'Publicista'),
    ('rrhh',                 'Recursos Humanos'),
    ('tecnólogo_medico',     'Tecnólogo/a médico/a'),
    ('tutor',                'Tutor/a particular'),
    ('otro',                 'Otro'),
]

CIUDADES = [
    ('santiago',       'Santiago'),
    ('valparaiso',     'Valparaíso'),
    ('vina_del_mar',   'Viña del Mar'),
    ('concepcion',     'Concepción'),
    ('la_serena',      'La Serena'),
    ('coquimbo',       'Coquimbo'),
    ('antofagasta',    'Antofagasta'),
    ('iquique',        'Iquique'),
    ('arica',          'Arica'),
    ('rancagua',       'Rancagua'),
    ('talca',          'Talca'),
    ('chillan',        'Chillán'),
    ('temuco',         'Temuco'),
    ('puerto_montt',   'Puerto Montt'),
    ('valdivia',       'Valdivia'),
    ('osorno',         'Osorno'),
    ('punta_arenas',   'Punta Arenas'),
    ('calama',         'Calama'),
    ('copiapo',        'Copiapó'),
    ('los_andes',      'Los Andes'),
    ('san_antonio',    'San Antonio'),
    ('quilpue',        'Quilpué'),
    ('villa_alemana',  'Villa Alemana'),
    ('curico',         'Curicó'),
    ('linares',        'Linares'),
    ('san_felipe',     'San Felipe'),
    ('melipilla',      'Melipilla'),
    ('talcahuano',     'Talcahuano'),
    ('coronel',        'Coronel'),
    ('angol',          'Angol'),
]

ROL_CHOICES = [
    ('estudiante', 'Estudiante'),
    ('profesor',   'Profesor'),
]
